name = "The Real New World"
author = "Singlain"
version = "0.5.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c956147afd2834979f7c23a478ab6480ffdce29f06bd596049dde196b22039aa"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
