name = "The Real New World"
author = "Singlain"
version = "0.7.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09d0e95a347ccddc02597c97dbc2ee219934791c606194b30f948ddc41b96bd8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
