name = "The Real New World"
author = "Singlain"
version = "0.5.1-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "145e02acd7b9ce9a703731d13fbc46cd97cd1a0b4897673a44cfa03efe642613"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
