name = "The Real New World"
author = "Singlain"
version = "0.8.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3853a7a430a636ee5cce96c268d34d1fd5550da31d3668852acdc993b34a837f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
