name = "The Real New World"
author = "Singlain"
version = "0.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "662b4a18907b090b2dc77005f78ba2ae2373e9738f7dfccae0e29ebe64be8084"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
