name = "The Real New World"
author = "Singlain"
version = "0.5.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de73255fb77c224a0b23884e026c8357fc6ae6273a3277f4008763059c9900d9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
