name = "The Real New World"
author = "Singlain"
version = "0.5.1-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "197544fbed92b9c1843c2fb2d885a1bcadceb061eb1520c70ce8a4fff2dc79ee"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
