name = "The Real New World"
author = "Singlain"
version = "0.6.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9c81ea5ec2ca41a260c3b99160eba245b8c77d0b2808dabb33589d742d255ec"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
