name = "The Real New World"
author = "Singlain"
version = "0.5.1-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "405b5f7aca523da2faec0c57c5a80a169f235ea5fbd58788edcef316d5dbcbab"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
