name = "The Real New World"
author = "Singlain"
version = "0.5.2-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "903d610bbf3aad7f2a1fb68b246cfa445937fa5d419566256375887ed9af5735"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
