name = "The Real New World"
author = "Singlain"
version = "0.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81ec86845de4dfe64fa8ea5105263aee844b59dacda0f185c7765a8597d62d09"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
