minY = -55
maxY = 30
disableVanillaMineshafts = true

[spawnRates]
lanternSpawnRate = 0.0067
torchSpawnRate = 0.02
workstationSpawnRate = 0.003
workstationDungeonSpawnRate = 0.25
smallShaftSpawnRate = 0.03
cobwebSpawnRate = 0.01
smallShaftChestMinecartSpawnRate = 0.00125
mainShaftChestMinecartSpawnRate = 0.01
smallShaftTntMinecartSpawnRate = 0.0024999999441206455
mainShaftTntMinecartSpawnRate = 0.0024999999441206455
zombieVillagerRoomSpawnChance = 0
smallShaftPieceChainLength = 9

[ores]
enabled = true
cobble = 75
coal = 30
iron = 10
redstone = 0
gold = 2
lapis = 3
emerald = 1
diamond = 1
