#Show player coordinates on the death screen.
#Default Value: true
death_screen_coordinates = true
#Add information about the last death position to the recovery compass tooltip.
#Default Value: true
recovery_compass_tooltip = false
