#Allowed Values: FIRST, MIDDLE, LAST
weaponCoolDownImportance = "MIDDLE"
disablePickaxesAndShovels = true
disableAxes = true
showBlockBreaking = true
showRangeWeaponDraw = true
showItemCooldowns = true
showFoodAndPotions = true
showSleep = true
showItemContainerFullness = false
