#Allowed Values: FIRST, MIDDLE, LAST
weaponCoolDownImportance = "FIRST"
disablePickaxesAndShovels = true
disableAxes = false
showBlockBreaking = true
showRangeWeaponDraw = true
showItemCooldowns = true
showFoodAndPotions = true
showSleep = true
showItemContainerFullness = false
