enablePinning = true
keepCentered = true
settingsButton = false
enableBook = true

[newRecipes]
unlockAll = true
enableBounce = false

[instantCraft]
showButton = true
enabled = false

[alternativeRecipes]
onHover = true
noGrouped = false

[scrolling]
enableScrolling = true
scrollAround = false
